deployments:
  cohere_platform:
    api_key:
  sagemaker:
    access_key:
    secret_key:
    session_token:
  azure:
    api_key:
  bedrock:
    access_key:
    secret_key:
    session_token:
database:
  # Migrate access token, used to authenticate requests to the migrate endpoint.
  # You can generate it using some random string generator.
  migrate_token:
tools:
  tavily:
    api_key:
  wolfram_alpha:
    app_id:
  compass:
    username:
    password:
  google_drive:
    client_id:
    client_secret:
    developer_key:
auth:
  secret_key:
  google_oauth:
    client_id:
    client_secret:
  oidc:
    client_id:
    client_secret:
    well_known_endpoint:
